development:
  adapter: postgresql
  database: create_misc_api_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: create_misc_api_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: create_misc_api_production
  pool: 5
  timeout: 5000
  username: carl
  password: 120622
